Repository redpanda-data/redpanda-operator, pull requests merged in 2025-06, with the labels that each got.

#887 Ensure that we periodically reconcile
  .changes/unreleased/operator-Changed-20250605-122221.yaml
  operator/CHANGELOG.md
  operator/internal/controller/redpanda/redpanda_controller.go
  operator/internal/controller/vectorized/cluster_controller.go
Labels: run-kuttl-v1

#894 [release/v25.1.x] operator: fix nil deference in `setupLicense`
  .changes/unreleased/operator-Fixed-20250606-132924.yaml
  operator/CHANGELOG.md
  operator/internal/controller/redpanda/redpanda_controller.go
Labels: backport

#885 gotohelm: handle various Kubernetes types in `helmette.Unwrap`
  gotohelm/helmette/shims.go
  gotohelm/helmette/shims_test.go
Labels: no-changelog

#900 [release/v25.1.x] ci: automatically retry acceptance and integration tests 3 times
  .buildkite/testsuite.yml
  gen/pipeline/helpers.go
  gen/pipeline/pipeline.go
Labels: backport

#901 [release/v2.4.x] ci: automatically retry acceptance and integration tests 3 times
  .buildkite/testsuite.yml
  gen/pipeline/helpers.go
  gen/pipeline/pipeline.go
Labels: backport

#905 [release/v2.3.x] operator: correct rack awareness permissions
  .changes/unreleased/operator-Fixed-20250609-152934.yaml
  acceptance/features/cluster.feature
  acceptance/steps/register.go
  acceptance/steps/rpk.go
  operator/CHANGELOG.md
  operator/chart/rbac.go
  operator/chart/templates/_rbac.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
Labels: backport

#904 [release/v2.4.x] operator: correct rack awareness permissions
  .changes/unreleased/operator-Fixed-20250609-152934.yaml
  acceptance/features/cluster.feature
  acceptance/steps/register.go
  acceptance/steps/rpk.go
  operator/CHANGELOG.md
  operator/chart/rbac.go
  operator/chart/templates/_rbac.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
Labels: backport

#908 [release/v2.4.x] operator: Fix missing https port in operator container definition
  .changes/unreleased/operator-Fixed-20250605-185548.yaml
  operator/CHANGELOG.md
  operator/chart/deployment.go
  operator/chart/templates/_deployment.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
Labels: backport

#909 [release/v2.3.x] operator: Fix missing https port in operator container definition
  .changes/unreleased/operator-Fixed-20250605-185548.yaml
  operator/CHANGELOG.md
  operator/chart/deployment.go
  operator/chart/templates/_deployment.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
Labels: backport

#914 Revert "PVC Unbinder: do not clear claimRef"
  operator/cmd/run/run.go
  operator/internal/controller/pvcunbinder/pvcunbinder.go
Labels: no-changelog

#913 operator: Set condition to mount ca.crt based on self sign function
  operator/pkg/resources/certmanager/type_helpers.go
  operator/pkg/resources/certmanager/type_helpers_test.go
Labels: no-changelog

#916 [release/v2.4.x] PVCUnbinder: Restore and flag claimRef clearing
  operator/cmd/run/run.go
  operator/internal/controller/pvcunbinder/pvcunbinder.go
Labels: backport

#919 [release/v25.1.x] operator: Set condition to mount ca.crt based on self sign function
  operator/pkg/resources/certmanager/type_helpers.go
  operator/pkg/resources/certmanager/type_helpers_test.go
Labels: backport

#918 operator: handle `ServiceMonitorList`'s Items
  Taskfile.yml
  harpoon/go.sum
  operator/internal/lifecycle/client.go
  pkg/go.mod
  pkg/go.sum
  pkg/kube/generics.go
  pkg/kube/generics_test.go
Labels: no-changelog

#920 [release/v25.1.x] operator: handle `ServiceMonitorList`'s Items
  Taskfile.yml
  harpoon/go.sum
  operator/internal/lifecycle/client.go
  pkg/go.mod
  pkg/go.sum
  pkg/kube/generics.go
  pkg/kube/generics_test.go
Labels: backport

#928 Add "Release On Tag" GHA
  .github/workflows/release.yml
  CONTRIBUTING.md
Labels: no-changelog

#932 [release/v2.3.x] CHANGELOGs: don't include unreleased changed
  Taskfile.yml
  charts/redpanda/CHANGELOG.md
  operator/CHANGELOG.md
Labels: backport

#931 [release/v2.4.x] CHANGELOGs: don't include unreleased changed
  Taskfile.yml
  charts/redpanda/CHANGELOG.md
  go.work.sum
  operator/CHANGELOG.md
Labels: backport

#936 Correct "Release on Tag" GHA
  .changie.yaml
  .github/workflows/release.yml
  CONTRIBUTING.md
  operator/chart/Chart.yaml
  operator/chart/README.md
  operator/chart/chart_test.go
  operator/chart/testdata/template-cases.golden.txtar
Labels: no-changelog

#939 v1: fix admin-api TLS mounting
  operator/pkg/resources/certmanager/type_helpers.go
Labels: no-changelog

#947 [release/v2.3.x] v1: fix admin-api TLS mounting
  operator/pkg/resources/certmanager/type_helpers.go
Labels: backport

#946 [release/v2.4.x] v1: fix admin-api TLS mounting
  operator/pkg/resources/certmanager/type_helpers.go
Labels: backport
