Repository redpanda-data/redpanda-operator, pull requests merged in 2025-05, with the labels that each got.

#792 [release/v2.3.x] operator: bump `go-git` from v5.11.0 to v5.13.0
  gen/go.mod
  gen/go.sum
  licenses/third_party.md
  operator/go.mod
  operator/go.sum
Labels: backport

#791 [release/v2.3.x] operator: over scope RBAC by default for backwards compat
  .changes/unreleased/operator-Added-20250430-130846.yaml
  operator/CHANGELOG.md
  operator/chart/README.md
  operator/chart/chart_test.go
  operator/chart/files/rbac/legacypermissions.ClusterRole.yaml
  operator/chart/files/rbac/legacypermissions.Role.yaml
  operator/chart/files/rbac/v2-manager.Role.yaml
  operator/chart/rbac.go
  operator/chart/templates/_rbac.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
  operator/chart/values.go
  operator/chart/values.schema.json
  operator/chart/values.yaml
  operator/chart/values_partial.gen.go
  operator/config/rbac/bases/operator/role.yaml
  operator/config/rbac/itemized/legacypermissions.yaml
  operator/config/rbac/itemized/v2-manager.yaml
  operator/internal/controller/legacypermissions/doc.go
  operator/internal/controller/legacypermissions/legacypermissions_test.go
  operator/internal/controller/redpanda/redpanda_controller.go
  operator/internal/controller/redpanda/redpanda_controller_test.go
  operator/internal/controller/redpanda/testdata/role.yaml
  taskfiles/k8s.yml
Labels: backport

#797 Change icon URI to new place
  charts/connectors/Chart.yaml
  charts/console/Chart.yaml
  charts/redpanda/Chart.yaml
Labels: no-changelog, v2.4.x, v2.3.x

#800 pkg: Fix helm locate functionality
  pkg/helm/helm.go
Labels: no-changelog

#810 operator: enable `rbac.createAdditionalControllerCRs` by default
  acceptance/main_test.go
  operator/chart/README.md
  operator/chart/chart_test.go
  operator/chart/testdata/template-cases.golden.txtar
  operator/chart/values.yaml
Labels: no-changelog

#803 Enable use of Node and Cluster config separately
  operator/pkg/clusterconfiguration/cel_patcher.go
  operator/pkg/clusterconfiguration/configuration_cluster.go
  operator/pkg/clusterconfiguration/configuration_combined.go
  operator/pkg/clusterconfiguration/configuration_node.go
Labels: no-changelog, run-kuttl-v1

#798 [release/v2.3.x] Change icon URI to new place
  charts/connectors/Chart.yaml
  charts/console/Chart.yaml
  charts/redpanda/Chart.yaml
Labels: backport, no-changelog

#799 [release/v2.4.x] Change icon URI to new place
  charts/connectors/Chart.yaml
  charts/console/Chart.yaml
  charts/redpanda/Chart.yaml
Labels: backport, no-changelog

#815 v1: fix upgrade of older clusters
  .changes/unreleased/operator-Fixed-20250506-111303.yaml
  .changes/unreleased/operator-Fixed-20250506-111414.yaml
  operator/CHANGELOG.md
  operator/pkg/resources/statefulset.go
Labels: run-kuttl-v1

#816 [release/v2.4.x] v1: fix upgrade of older clusters (#815)
  .changes/unreleased/operator-Fixed-20250506-111303.yaml
  .changes/unreleased/operator-Fixed-20250506-111414.yaml
  operator/CHANGELOG.md
  operator/pkg/resources/statefulset.go
Labels: backport

#465 operator/pkg/vcluster: add support for vClusters
  ci/overlay.nix
  ci/vcluster.nix
  flake.nix
  gen/go.mod
  operator/api/redpanda/v1alpha2/redpanda_clusterspec_types.go
  operator/api/redpanda/v1alpha2/redpanda_types_test.go
  operator/api/redpanda/v1alpha2/testdata/crd-docs.adoc
  operator/config/crd/bases/cluster.redpanda.com_redpandas.yaml
  operator/go.mod
  operator/go.sum
  operator/internal/probes/broker_test.go
  operator/internal/testenv/owned_client.go
  operator/internal/testenv/testenv.go
  operator/pkg/k3d/k3d.go
  operator/pkg/vcluster/vcluster.go
  operator/pkg/vcluster/vcluster_test.go
Labels: no-changelog

#820 v1: fix typo in getConfiguratorArgs
  operator/pkg/resources/statefulset.go
Labels: no-changelog

#770 Acceptance tests changes #750
  acceptance/features/cluster.feature
  acceptance/features/decommissioning.feature
  acceptance/features/scaling.feature
  acceptance/go.mod
  acceptance/main_test.go
  acceptance/steps/cluster.go
  acceptance/steps/register.go
  acceptance/steps/scaling.go
  acceptance/steps/service.go
  operator/internal/lifecycle/pool.go
  operator/tests/e2e-v2/decommission/00-assert-create-redpanda.yaml
  operator/tests/e2e-v2/decommission/00-create-redpanda.yaml
  operator/tests/e2e-v2/decommission/01-assert-scale-down-redpanda.yaml
  operator/tests/e2e-v2/decommission/01-scale-down-redpanda.yaml
  operator/tests/e2e-v2/decommission/02-assert-scale-down-redpanda.yaml
  operator/tests/e2e-v2/decommission/02-scale-down-redpanda.yaml
  operator/tests/e2e-v2/decommission/03-assert.yaml
  operator/tests/e2e-v2/decommission/03-delete-redpandas.yaml
  operator/tests/e2e-v2/node-deleted/00-assert-create-redpanda.yaml
  operator/tests/e2e-v2/node-deleted/00-create-redpanda.yaml
  operator/tests/e2e-v2/node-deleted/01-assert-delete-node.yaml
  operator/tests/e2e-v2/node-deleted/01-delete-node.yaml
  operator/tests/e2e-v2/node-deleted/02-assert-delete-node-again.yaml
  operator/tests/e2e-v2/node-deleted/02-delete-node-again.yaml
  operator/tests/e2e-v2/node-deleted/03-assert.yaml
  operator/tests/e2e-v2/node-deleted/03-delete-redpandas.yaml
  operator/tests/e2e-v2/node-deleted/04-assert.yaml
  operator/tests/e2e-v2/node-deleted/04-recreate-nodes.yaml
  operator/tests/e2e-v2/resource-redpanda-crud/00-assert-create-redpanda.yaml
  operator/tests/e2e-v2/resource-redpanda-crud/00-create-redpanda.yaml
  operator/tests/e2e-v2/resource-redpanda-crud/01-assert-update-chart-version.yaml
  operator/tests/e2e-v2/resource-redpanda-crud/01-update-chart-version.yaml
  operator/tests/e2e-v2/resource-redpanda-crud/02-assert-update-clusterspec.yaml
  operator/tests/e2e-v2/resource-redpanda-crud/02-update-clusterspec.yaml
  operator/tests/e2e-v2/resource-redpanda-crud/03-assert.yaml
  operator/tests/e2e-v2/resource-redpanda-crud/03-delete-redpandas.yaml
  operator/tests/e2e-v2/resource-topic-crud/00-assert-create-redpanda.yaml
  operator/tests/e2e-v2/resource-topic-crud/00-create-redpanda.yaml
  operator/tests/e2e-v2/resource-topic-crud/01-assert-create-topic.yaml
  operator/tests/e2e-v2/resource-topic-crud/01-create-topic.yaml
  operator/tests/e2e-v2/resource-topic-crud/02-assert-update-topic.yaml
  operator/tests/e2e-v2/resource-topic-crud/02-update-topic-configuration.yaml
  operator/tests/e2e-v2/resource-topic-crud/03-assert-increase-topic-partitions.yaml
  operator/tests/e2e-v2/resource-topic-crud/03-increase-topic-partitions.yaml
  operator/tests/e2e-v2/resource-topic-crud/04-assert-increase-topic-replication-factor.yaml
  operator/tests/e2e-v2/resource-topic-crud/04-increase-topic-replication-factor.yaml
  operator/tests/e2e-v2/resource-topic-crud/05-assert-overwrite-topic-name.yaml
  operator/tests/e2e-v2/resource-topic-crud/05-overwrite-topic-name.yaml
  operator/tests/e2e-v2/resource-topic-crud/06-delete-redpandas.yaml
  operator/tests/e2e-v2/upgrade-values-check/00-assert-create-redpanda.yaml
  operator/tests/e2e-v2/upgrade-values-check/00-create-redpanda.yaml
  operator/tests/e2e-v2/upgrade-values-check/01-assert-upgrade-redpanda.yaml
  operator/tests/e2e-v2/upgrade-values-check/01-upgrade-redpanda.yaml
  operator/tests/e2e-v2/upgrade-values-check/02-assert.yaml
  operator/tests/e2e-v2/upgrade-values-check/02-delete-redpandas.yaml
Labels: no-changelog

#826 Wrap authFromDot in a panic handler
  charts/redpanda/client/client.go
Labels: no-changelog

#825 pkg/helm: gracefully shutdown on timeout
  pkg/helm/helm.go
  pkg/helm/helm_test.go
Labels: no-changelog

#829 Remove src symlink
  src/go/k8s
Labels: no-changelog

#823 Add operator upgrade acceptance test
  Taskfile.yml
  acceptance/features/operator-upgrades.feature
  acceptance/main_test.go
  acceptance/steps/cluster.go
  acceptance/steps/helpers.go
  acceptance/steps/operator.go
  acceptance/steps/register.go
  harpoon/internal/testing/helm.go
  harpoon/internal/testing/tags.go
  harpoon/internal/tracking/features.go
  harpoon/internal/tracking/scenarios.go
  harpoon/suite.go
  harpoon/types.go
Labels: no-changelog

#835 v1: OperatorQuiescent requires ClusterConfigured
  .changes/unreleased/operator-Changed-20250519-121920.yaml
  operator/CHANGELOG.md
  operator/internal/controller/vectorized/cluster_controller.go
Labels: run-kuttl-v1

#837 [release/v2.3.x] v1: OperatorQuiescent requires ClusterConfigured (#835)
  .changes/unreleased/operator-Changed-20250519-121920.yaml
  licenses/third_party.md
  operator/CHANGELOG.md
  operator/internal/controller/vectorized/cluster_controller.go
Labels: backport

#838 bump `go-licenses` to v2.0.0-alpha.1
  ci/go-licenses.nix
  ci/overlay.nix
  licenses/third_party.md
Labels: no-changelog

#842 Add back rate-limiting to cluster configuration and license reconciliation
  gen/status/templates/status.tpl
  operator/internal/controller/redpanda/redpanda_controller.go
  operator/internal/statuses/zz_generated_status.go
Labels: no-changelog

#844 Switch from Quiesced to Stable for waitUntilReady check
  operator/internal/controller/redpanda/redpanda_controller_test.go
  operator/internal/testenv/testenv.go
  pkg/kube/dialer.go
Labels: no-changelog

#846 operator: always mount service account token volume
  .changes/unreleased/operator-Fixed-20250521-111352.yaml
  operator/CHANGELOG.md
  operator/chart/deployment.go
  operator/chart/templates/_deployment.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
Labels: v2.4.x, v2.3.x

#847 [release/v2.4.x] operator: always mount service account token volume
  .changes/unreleased/operator-Fixed-20250521-111352.yaml
  operator/CHANGELOG.md
  operator/chart/deployment.go
  operator/chart/templates/_deployment.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
Labels: backport

#851 OTEL metrics provider
  .buildkite/testsuite.yml
  acceptance/go.mod
  acceptance/go.sum
  charts/connectors/go.mod
  charts/connectors/go.sum
  charts/console/go.mod
  charts/console/go.sum
  charts/redpanda/go.mod
  charts/redpanda/go.sum
  gen/go.mod
  gen/go.sum
  gen/pipeline/helpers.go
  go.work.sum
  gotohelm/go.mod
  gotohelm/go.sum
  gotohelm/testdata/src/example/go.mod
  gotohelm/testdata/src/example/go.sum
  harpoon/go.mod
  harpoon/go.sum
  licenses/third_party.md
  licenseupdater/go.mod
  licenseupdater/go.sum
  operator/go.mod
  operator/go.sum
  pkg/go.mod
  pkg/go.sum
  pkg/otelutil/metrics/meter.go
  pkg/otelutil/otelutil.go
  pkg/otelutil/otlpfile/otlpfile.go
Labels: no-changelog

#863 always mount access token
  operator/chart/deployment.go
  operator/chart/templates/_deployment.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
Labels: no-changelog

#869 Add v1alpha3 nodepools and begin plumbing through controller
  operator/api/applyconfiguration/redpanda/v1alpha3/brokertemplate.go
  operator/api/applyconfiguration/redpanda/v1alpha3/clusterref.go
  operator/api/applyconfiguration/redpanda/v1alpha3/embeddednodepoolspec.go
  operator/api/applyconfiguration/redpanda/v1alpha3/nodepool.go
  operator/api/applyconfiguration/redpanda/v1alpha3/nodepoolspec.go
  operator/api/applyconfiguration/redpanda/v1alpha3/nodepoolstatus.go
  operator/api/applyconfiguration/redpanda/v1alpha3/podtemplate.go
  operator/api/applyconfiguration/redpanda/v1alpha3/valuesource.go
  operator/api/redpanda/v1alpha3/common.go
  operator/api/redpanda/v1alpha3/groupversion_info.go
  operator/api/redpanda/v1alpha3/nodepool_types.go
  operator/api/redpanda/v1alpha3/zz_generated.deepcopy.go
  operator/config/crd/bases/cluster.redpanda.com_nodepools.yaml
  operator/config/crd/bases/crds_test.go
  operator/internal/controller/redpanda/redpanda_controller.go
  operator/internal/lifecycle/client.go
  operator/internal/lifecycle/v2.go
  operator/internal/lifecycle/v2_node_pools.go
  operator/internal/lifecycle/v2_ownership.go
  operator/internal/lifecycle/v2_simple_resources.go
  operator/internal/lifecycle/v2_status.go
  operator/internal/lifecycle/v2_test.go
  taskfiles/k8s.yml
Labels: no-changelog

#870 Add NodePool rendering support scaffold
  acceptance/go.mod
  charts/redpanda/chart.go
  charts/redpanda/configmap.tpl.go
  charts/redpanda/console.tpl.go
  charts/redpanda/go.mod
  charts/redpanda/go.sum
  charts/redpanda/poddisruptionbudget.go
  charts/redpanda/render.go
  charts/redpanda/secrets.go
  charts/redpanda/service.loadbalancer.go
  charts/redpanda/statefulset.go
  charts/redpanda/templates/_chart.go.tpl
  charts/redpanda/templates/_configmap.go.tpl
  charts/redpanda/templates/_console.go.tpl
  charts/redpanda/templates/_poddisruptionbudget.go.tpl
  charts/redpanda/templates/_render.go.tpl
  charts/redpanda/templates/_secrets.go.tpl
  charts/redpanda/templates/_service.loadbalancer.go.tpl
  charts/redpanda/templates/_statefulset.go.tpl
  gen/go.mod
  operator/api/applyconfiguration/redpanda/v1alpha3/redpanda.go
  operator/api/applyconfiguration/redpanda/v1alpha3/redpandalicensestatus.go
  operator/api/applyconfiguration/redpanda/v1alpha3/redpandastatus.go
  operator/api/redpanda/v1alpha3/cluster_types.go
  operator/api/redpanda/v1alpha3/zz_generated.deepcopy.go
  operator/go.mod
  operator/statuses.yaml
Labels: no-changelog

#871 Be more lenient when parsing configuration values
  .changes/unreleased/operator-Changed-20250529-110428.yaml
  operator/CHANGELOG.md
  operator/pkg/clusterconfiguration/expander.go
Labels: run-kuttl-v1
