Repository redpanda-data/redpanda-operator, pull requests merged in 2025-04, with the labels that each got.

#568 Basic Lifecycle Management Interfaces + v2 Concrete Implementations
  operator/go.mod
  operator/internal/lifecycle/client.go
  operator/internal/lifecycle/client_test.go
  operator/internal/lifecycle/constants.go
  operator/internal/lifecycle/helpers.go
  operator/internal/lifecycle/helpers_test.go
  operator/internal/lifecycle/interfaces.go
  operator/internal/lifecycle/interfaces_test.go
  operator/internal/lifecycle/pool.go
  operator/internal/lifecycle/pool_test.go
  operator/internal/lifecycle/testdata/cases.pools.golden.txtar
  operator/internal/lifecycle/testdata/cases.resources.golden.txtar
  operator/internal/lifecycle/testdata/cases.txtar
  operator/internal/lifecycle/v2.go
  operator/internal/lifecycle/v2_node_pools.go
  operator/internal/lifecycle/v2_ownership.go
  operator/internal/lifecycle/v2_simple_resources.go
  operator/internal/lifecycle/v2_status.go
  operator/internal/lifecycle/v2_test.go
Labels: no-changelog

#618 Bump common-go secrets dependency to fix snyk issues
  pkg/go.mod
  pkg/go.sum
Labels: no-changelog

#621 bk: add `post-checkout` hook to cleanup leftover containers
  .buildkite/hooks/post-checkout
Labels: no-changelog

#631 [release/v2.4.x] bk: add pre-exit hook to cleanup containers (#621)
  .buildkite/hooks/post-checkout
Labels: backport

#630 [release/v25.1.x] bk: add pre-exit hook to cleanup containers (#621)
  .buildkite/hooks/post-checkout
Labels: backport

#638 pkg: fix `TestToolVersions` on macos
  pkg/lint/lint_test.go
  pkg/lint/testdata/tool-versions.txtar
Labels: no-changelog, v25.1.x, v2.4.x, v2.3.x

#639 [release/v25.1.x] [K8S-534] redpanda: drop deprecated license fields
  .changes/unreleased/charts-redpanda-Removed-20250328-140428.yaml
  charts/redpanda/CHANGELOG.md
  charts/redpanda/README.md
  charts/redpanda/console.tpl.go
  charts/redpanda/post_install_upgrade_job.go
  charts/redpanda/post_install_upgrade_job_test.go
  charts/redpanda/templates/_console.go.tpl
  charts/redpanda/templates/_helpers.tpl
  charts/redpanda/templates/_post-install-upgrade-job.go.tpl
  charts/redpanda/templates/_values.go.tpl
  charts/redpanda/values.go
  charts/redpanda/values.schema.json
  charts/redpanda/values.yaml
  charts/redpanda/values_partial.gen.go
Labels: backport

#637 charts/console: cut release v3.0-k8s1-beta.1
  .changes/charts/console/v3.0-k8s1-beta.1.md
  charts/console/CHANGELOG.md
  charts/console/Chart.yaml
  charts/console/README.md
  charts/console/chart_test.go
  charts/console/testdata/template-cases.golden.txtar
Labels: no-changelog, v25.1.x

#646 [release/v25.1.x] charts/console: cut release v3.0-k8s1-beta.1
  .changes/charts/console/v3.0-k8s1-beta.1.md
  charts/console/CHANGELOG.md
  charts/console/Chart.yaml
  charts/console/README.md
  charts/console/chart_test.go
  charts/console/testdata/template-cases.golden.txtar
Labels: backport

#643 [release/v25.1.x] pkg: fix `TestToolVersions` on macos
  pkg/lint/lint_test.go
  pkg/lint/testdata/tool-versions.txtar
Labels: backport

#645 [release/v2.3.x] pkg: fix `TestToolVersions` on macos
  pkg/lint/lint_test.go
  pkg/lint/testdata/tool-versions.txtar
Labels: backport

#651 Bump common-go secrets dependency to fix snyk issues
  gen/go.mod
  gen/go.sum
  licenses/third_party.md
  operator/go.mod
  operator/go.sum
Labels: no-changelog

#653 add cloud secrets expansion into v1 operator
  licenses/third_party.md
  operator/cmd/configurator/bootstrap.go
  operator/cmd/configurator/configurator.go
  operator/cmd/run/run.go
  operator/go.mod
  operator/go.sum
  operator/internal/controller/vectorized/cluster_controller.go
  operator/internal/controller/vectorized/cluster_controller_configuration.go
  operator/pkg/clusterconfiguration/expander.go
  operator/pkg/resources/configuration/configuration.go
  operator/pkg/resources/configuration/configuration_test.go
  operator/pkg/secrets/secrets.go
  operator/pkg/secrets/secrets_test.go
  pkg/go.mod
  pkg/go.sum
Labels: no-changelog

#658 remove references to `release/v25.1.x`
  .backportrc.json
  .github/branches.yml
  CONTRIBUTING.md
  README.md
Labels: no-changelog

#661 [release/v2.4.x] temporarily disable kuttl-v1 tests
  .buildkite/testsuite.yml
  gen/pipeline/pipeline.go
Labels: backport

#664 [release/v2.3.x] Update console operator and connectors to use latest pkg and separate gotohelm (#654)
  charts/connectors/chart.go
  charts/connectors/chart_test.go
  charts/connectors/deployment.go
  charts/connectors/go.mod
  charts/connectors/go.sum
  charts/connectors/helpers.go
  charts/connectors/podmonitor.go
  charts/connectors/rules.go
  charts/connectors/service.go
  charts/connectors/serviceaccount.go
  charts/connectors/values.go
  charts/console/chart.go
  charts/console/chart_test.go
  charts/console/configmap.go
  charts/console/deployment.go
  charts/console/go.mod
  charts/console/go.sum
  charts/console/helpers.go
  charts/console/hpa.go
  charts/console/ingress.go
  charts/console/notes.go
  charts/console/rules.go
  charts/console/secret.go
  charts/console/service.go
  charts/console/serviceaccount.go
  charts/operator/certificates.go
  charts/operator/chart.go
  charts/operator/configmap.go
  charts/operator/deployment.go
  charts/operator/go.mod
  charts/operator/go.sum
  charts/operator/helpers.go
  charts/operator/rbac.go
  charts/operator/rules.go
  charts/operator/service.go
  charts/operator/serviceaccount.go
  charts/operator/servicemonitor.go
  charts/redpanda/go.mod
  charts/redpanda/go.sum
  gen/go.mod
  gen/go.sum
  gotohelm/go.mod
  gotohelm/go.sum
  pkg/gotohelm/transpiler.go
  pkg/lint/lint_test.go
Labels: backport

#667 remove concept of "external/internal" versions
  .changes/charts/console/v3.0.0-beta.1.md
  .changes/charts/console/v3.0.0.md
  .changie.yaml
  CONTRIBUTING.md
  Taskfile.yml
  charts/console/CHANGELOG.md
  charts/console/Chart.yaml
  charts/console/README.md
  charts/console/chart_test.go
  charts/console/testdata/template-cases.golden.txtar
  ci/scripts/version.sh
Labels: no-changelog

#668 Bump golang.org/x/net to v0.38.0
  acceptance/go.mod
  acceptance/go.sum
  gen/go.mod
  gen/go.sum
  harpoon/go.mod
  harpoon/go.sum
  licenses/third_party.md
  operator/go.mod
  operator/go.sum
Labels: no-changelog, v2.4.x, v2.3.x

#669 [release/2.3.x] Bump golang.org/x/net to v0.38.0
  acceptance/go.mod
  acceptance/go.sum
  harpoon/go.mod
  harpoon/go.sum
  licenses/third_party.md
  operator/go.mod
  operator/go.sum
Labels: backport, no-changelog

#670 [release/2.4.x] Bump golang.org/x/net to v0.38.0
  acceptance/go.mod
  acceptance/go.sum
  harpoon/go.mod
  harpoon/go.sum
  licenses/third_party.md
  operator/go.mod
  operator/go.sum
Labels: backport, no-changelog

#627 Replace redpanda pinned version with local code in the operator repo.
  .golangci.yml
  operator/api/redpanda/v1alpha2/redpanda_types.go
  operator/api/redpanda/v1alpha2/redpanda_types_test.go
  operator/go.mod
  operator/go.sum
  operator/internal/controller/redpanda/redpanda_controller.go
  operator/internal/controller/redpanda/redpanda_controller_test.go
  operator/internal/controller/vectorized/cluster_controller.go
  operator/internal/controller/vectorized/test/suite_test.go
  operator/internal/lifecycle/testdata/cases.pools.golden.txtar
  operator/internal/lifecycle/testdata/cases.resources.golden.txtar
  operator/internal/lifecycle/v2_node_pools.go
  operator/internal/lifecycle/v2_simple_resources.go
  operator/internal/lifecycle/v2_test.go
  operator/pkg/admin/admin.go
  operator/pkg/client/cluster.go
  operator/pkg/client/factory.go
  operator/pkg/client/spec_tls.go
  operator/pkg/console/admin.go
  operator/pkg/console/sasl.go
  operator/pkg/resources/statefulset.go
  operator/pkg/resources/statefulset_test.go
  operator/pkg/resources/statefulset_update_test.go
  operator/tests/e2e-v2/connectors/00-assert-create-redpanda.yaml
  operator/tests/e2e-v2/connectors/00-create-redpanda.yaml
  operator/tests/e2e-v2/connectors/01-assert.yaml
  operator/tests/e2e-v2/connectors/01-delete-redpandas.yaml
  operator/webhooks/redpanda/validate_enterprise_test.go
  pkg/lint/lint_test.go
Labels: no-changelog

#685 operator/chart: fix README.md generation
  operator/chart/README.md
  taskfiles/charts.yml
Labels: no-changelog, v2.4.x, v2.3.x

#682 [release/v2.3.x] operator/chart: remove `--configurator-tag` override
  operator/chart/testdata/template-cases.golden.txtar
  operator/chart/values.yaml
Labels: backport

#686 operator/chart: sync RBAC with redpanda chart
  .changes/unreleased/operator-Fixed-20250409-152100.yaml
  charts/redpanda/rbac_test.go
  operator/CHANGELOG.md
  operator/chart/chart_test.go
  operator/chart/files/three_node_cluster.yaml
  operator/chart/files/three_node_redpanda.yaml
  operator/chart/rbac.go
  operator/chart/templates/_rbac.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
  operator/config/rbac/bases/operator/role.yaml
  operator/config/rbac/itemized/decommission.yaml
  operator/config/rbac/itemized/rpk-debug-bundle.yaml
  operator/config/rbac/itemized/v2-manager.yaml
  operator/internal/controller/decommissioning/statefulset_decomissioner.go
  operator/internal/controller/decommissioning/testdata/role.yaml
  operator/internal/controller/redpanda/redpanda_controller.go
  operator/internal/controller/rpkdebugbundle/doc.go
Labels: v2.4.x, v2.3.x

#687 [release/v2.4.x] bk: skip removing images from hook (#684)
  .buildkite/hooks/post-checkout
Labels: backport

#691 [release/v2.4.x] operator/chart: sync RBAC with redpanda chart
  .changes/unreleased/operator-Fixed-20250409-152100.yaml
  charts/redpanda/rbac_test.go
  operator/CHANGELOG.md
  operator/chart/chart_test.go
  operator/chart/files/three_node_cluster.yaml
  operator/chart/files/three_node_redpanda.yaml
  operator/chart/rbac.go
  operator/chart/templates/_rbac.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
  operator/config/rbac/bases/operator/role.yaml
  operator/config/rbac/itemized/decommission.yaml
  operator/config/rbac/itemized/rpk-debug-bundle.yaml
  operator/config/rbac/itemized/v2-manager.yaml
  operator/internal/controller/decommissioning/statefulset_decomissioner.go
  operator/internal/controller/decommissioning/testdata/role.yaml
  operator/internal/controller/redpanda/redpanda_controller.go
  operator/internal/controller/rpkdebugbundle/doc.go
Labels: backport

#689 [release/v2.4.x] operator/chart: fix README.md generation
  operator/chart/README.md
  taskfiles/charts.yml
Labels: backport

#690 [release/v2.3.x] operator/chart: fix README.md generation
  operator/chart/README.md
  taskfiles/charts.yml
Labels: backport

#692 [release/v2.3.x] operator/chart: sync RBAC with redpanda chart
  .changes/unreleased/operator-Fixed-20250409-152100.yaml
  charts/redpanda/rbac_test.go
  operator/CHANGELOG.md
  operator/chart/chart_test.go
  operator/chart/files/three_node_cluster.yaml
  operator/chart/files/three_node_redpanda.yaml
  operator/chart/rbac.go
  operator/chart/templates/_rbac.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
  operator/config/rbac/bases/operator/role.yaml
  operator/config/rbac/itemized/decommission.yaml
  operator/config/rbac/itemized/rpk-debug-bundle.yaml
  operator/config/rbac/itemized/v2-manager.yaml
  operator/internal/controller/decommissioning/statefulset_decomissioner.go
  operator/internal/controller/decommissioning/testdata/role.yaml
  operator/internal/controller/redpanda/redpanda_controller.go
  operator/internal/controller/rpkdebugbundle/doc.go
Labels: backport

#693 make scopes in console config optional
  operator/pkg/console/configmap_test.go
  operator/pkg/console/console.go
Labels: no-changelog

#698 [release/v2.3.x] make scopes in console config optional (#693)
  operator/pkg/console/configmap_test.go
  operator/pkg/console/console.go
Labels: backport

#699 [release/v2.4.x] make scopes in console config optional (#693)
  operator/pkg/console/configmap_test.go
  operator/pkg/console/console.go
Labels: backport

#696 Add back `go.work`
  .golangci.yml
  Taskfile.yml
  acceptance/go.mod
  acceptance/go.sum
  acceptance/rules.go
  alias/go.mod
  alias/go.sum
  alias/rules.go
  charts/connectors/go.mod
  charts/connectors/go.sum
  charts/connectors/rules.go
  charts/console/go.mod
  charts/console/go.sum
  charts/console/rules.go
  charts/redpanda/Chart.lock
  charts/redpanda/Chart.yaml
  charts/redpanda/README.md
  charts/redpanda/go.mod
  charts/redpanda/go.sum
  charts/redpanda/rules.go
  gen/go.mod
  gen/go.sum
  gen/rules.go
  go.work
  go.work.sum
  gotohelm/go.mod
  gotohelm/go.sum
  gotohelm/rules.go
  gotohelm/testdata/src/example/go.mod
  gotohelm/testdata/src/example/go.sum
  gotohelm/testdata/src/example/rules.go
  harpoon/go.mod
  harpoon/go.sum
  harpoon/rules.go
  licenses/third_party.md
  licenseupdater/go.mod
  licenseupdater/go.sum
  licenseupdater/rules.go
  operator/chart/rules.go
  operator/go.mod
  operator/go.sum
  operator/rules.go
  pkg/go.mod
  pkg/go.sum
  pkg/lint/rules/doc.go
  pkg/rules.go
  taskfiles/ci.yml
Labels: no-changelog

#700 fix GOROOT in nix
  flake.nix
Labels: no-changelog

#702 gotohelm: cut release v1.0.0
  .changie.yaml
  go.work.sum
  gotohelm/README.md
Labels: no-changelog

#703 [release/v2.3.x] operator/chart: fix nightly build
  taskfiles/k8s.yml
Labels: backport

#705 [release/v2.3.x] fix GOROOT in nix (#700)
  flake.nix
Labels: backport

#708 [release/v2.3.x] operator: Fix none strict json unmarshalling from std json library
  .changes/unreleased/operator-Fixed-20250411-215234.yaml
  operator/CHANGELOG.md
  operator/api/redpanda/v1alpha2/redpanda_types.go
  operator/api/redpanda/v1alpha2/redpanda_types_test.go
  operator/internal/controller/redpanda/redpanda_controller.go
Labels: backport

#713 operator: fix reconcile pod annotation
  operator/internal/controller/redpanda/redpanda_controller.go
  operator/internal/controller/redpanda/redpanda_controller_test.go
Labels: no-changelog

#717 pass in secret config to configurator
  operator/cmd/run/run.go
  operator/pkg/resources/statefulset.go
  operator/pkg/resources/statefulset_test.go
Labels: no-changelog, v2.4.x, v2.3.x

#707 [release/v2.4.x] operator: Fix none strict json unmarshalling from std json library
  .changes/unreleased/operator-Fixed-20250411-215234.yaml
  operator/CHANGELOG.md
  operator/api/redpanda/v1alpha2/redpanda_types.go
  operator/api/redpanda/v1alpha2/redpanda_types_test.go
  operator/internal/controller/redpanda/redpanda_controller.go
Labels: backport

#718 [release/v2.3.x] pass in secret config to configurator (#717)
  operator/cmd/run/run.go
  operator/pkg/resources/statefulset.go
  operator/pkg/resources/statefulset_test.go
Labels: backport

#711 [release/v2.4.x] annotate brokers with cluster config version to force a restart on config changes | operator: test that cluster configs are applied and cluster is restarted | operator: set ClusterConfigSynced to false when restart is required
  .changes/unreleased/operator-Fixed-20250408-141738.yaml
  operator/CHANGELOG.md
  operator/cmd/syncclusterconfig/sync.go
  operator/internal/controller/redpanda/redpanda_controller.go
  operator/internal/controller/redpanda/redpanda_controller_test.go
  operator/internal/controller/vectorized/cluster_controller_configuration.go
Labels: backport

#722 Optionally run kuttl-v1 tests
  .buildkite/testsuite.yml
  gen/pipeline/helpers.go
  gen/pipeline/pipeline.go
Labels: no-changelog

#732 BSD-proof `task:generate`
  taskfiles/k8s.yml
Labels: no-changelog

#733 Revert "BSD-proof `task:generate` (#732)"
  taskfiles/k8s.yml
Labels: no-changelog

#697 removed unused `chart-testing` dep
  Taskfile.yml
  ci/chart-testing.nix
  ci/overlay.nix
  flake.nix
  pkg/lint/lint_test.go
  taskfiles/charts.yml
Labels: v2.4.x, v2.3.x

#734 [release/v2.4.x] *: remove `kind` from integration tests
  Taskfile.yml
  charts/connectors/go.sum
  charts/console/go.mod
  charts/console/go.sum
  charts/redpanda/chart_test.go
  charts/redpanda/client_test.go
  charts/redpanda/go.mod
  charts/redpanda/go.sum
  gen/go.mod
  operator/pkg/k3d/k3d.go
  pkg/go.mod
  pkg/go.sum
  pkg/helm/helmtest/helmtest.go
Labels: backport

#741 make role arn optional
  operator/cmd/run/run.go
Labels: no-changelog

#744 [release/v2.3.x] make role arn optional (#741)
  operator/cmd/run/run.go
Labels: backport

#742 [release/v2.3.x] *: remove `kind` from integration tests
  Taskfile.yml
  charts/connectors/go.mod
  charts/connectors/go.sum
  charts/console/go.mod
  charts/console/go.sum
  charts/redpanda/chart_test.go
  charts/redpanda/client_test.go
  charts/redpanda/go.mod
  charts/redpanda/go.sum
  gen/go.mod
  gen/go.sum
  gotohelm/go.mod
  gotohelm/go.sum
  operator/pkg/k3d/k3d.go
  pkg/go.mod
  pkg/go.sum
  pkg/gotohelm/testdata/src/example/go.mod
  pkg/gotohelm/testdata/src/example/go.sum
  pkg/helm/helmtest/helmtest.go
Labels: backport

#745 Make ARN also optional in the operator
  operator/cmd/configurator/configurator.go
Labels: no-changelog

#747 [release/v2.3.x] Make ARN also optional in the operator
  operator/cmd/configurator/configurator.go
Labels: backport

#735 Add Typed Status Generation
  gen/main.go
  gen/status/cmd.go
  gen/status/helpers.go
  gen/status/status.go
  gen/status/structs.go
  gen/status/templates/status.tpl
  gen/status/templates/status_test.tpl
  operator/internal/statuses/zz_generated_status.go
  operator/internal/statuses/zz_generated_status_test.go
  operator/statuses.yaml
  taskfiles/k8s.yml
Labels: no-changelog

#604 V1 configuration refactor
  go.work.sum
  operator/api/vectorized/v1alpha1/cluster_types.go
  operator/cmd/configurator/bootstrap.go
  operator/cmd/configurator/configurator.go
  operator/cmd/configurator/fixup.go
  operator/config/crd/bases/redpanda.vectorized.io_clusters.yaml
  operator/go.mod
  operator/internal/controller/vectorized/cluster_controller.go
  operator/internal/controller/vectorized/cluster_controller_attached_resources.go
  operator/internal/controller/vectorized/cluster_controller_configuration.go
  operator/internal/controller/vectorized/test/cluster_controller_configuration_test.go
  operator/pkg/clusterconfiguration/cel_macros.go
  operator/pkg/clusterconfiguration/cel_patcher.go
  operator/pkg/clusterconfiguration/cel_patcher_test.go
  operator/pkg/clusterconfiguration/configuration_cluster.go
  operator/pkg/clusterconfiguration/configuration_combined.go
  operator/pkg/clusterconfiguration/configuration_node.go
  operator/pkg/clusterconfiguration/configuration_test.go
  operator/pkg/clusterconfiguration/expander.go
  operator/pkg/clusterconfiguration/serialization_test.go
  operator/pkg/resources/configmap.go
  operator/pkg/resources/configmap_test.go
  operator/pkg/resources/configuration.go
  operator/pkg/resources/configuration/configuration.go
  operator/pkg/resources/configuration/configuration_modes.go
  operator/pkg/resources/configuration/configuration_test.go
  operator/pkg/resources/configuration/serialization.go
  operator/pkg/resources/configuration/serialization_test.go
  operator/pkg/resources/resource_integration_test.go
  operator/pkg/resources/statefulset.go
  operator/pkg/resources/statefulset_test.go
  operator/pkg/resources/testdata/Complex_struct_in_additional_configuration.golden
  operator/pkg/resources/testdata/Primitive_object_in_additional_configuration.golden
  operator/pkg/resources/testdata/shadow_index_cache_directory.golden
  operator/tests/e2e/additional-configuration/01-verify-config.yaml
  operator/tests/e2e/additional-configuration/03-verify-config-changed.yaml
  operator/tests/e2e/additional-configuration/05-verify-config-changed.yaml
  operator/tests/e2e/additional-configuration/verify-config-dev.sh
  operator/tests/e2e/additional-configuration/verify-config-v24.2.sh
  operator/tests/e2e/additional-configuration/verify-config.sh
  operator/tests/e2e/centralized-configuration-injected-ref/00-redpanda-cluster.yaml
  operator/tests/e2e/centralized-configuration-injected-ref/01-assert.yaml
  operator/tests/e2e/centralized-configuration-injected-ref/01-probe.yaml
  operator/tests/e2e/centralized-configuration-injected-ref/01-redpanda-cluster-change.yaml
  operator/tests/e2e/centralized-configuration-injected-ref/02-assert.yaml
  operator/tests/e2e/centralized-configuration-injected-ref/02-redpanda-cluster-change.yaml
  operator/tests/e2e/centralized-configuration-injected-ref/03-assert.yaml
  operator/tests/e2e/centralized-configuration-injected-ref/03-probe.yaml
  operator/tests/e2e/centralized-configuration-injected-ref/04-assert.yaml
  operator/tests/e2e/centralized-configuration-injected-ref/04-clean.yaml
  operator/tests/e2e/multi-external-listeners/verify-config-v24.2.sh
Labels: no-changelog, run-kuttl-v1

#753 [release/v2.4.x] operator: add annotation feature flag for restart cluster on config change (#748)
  operator/cmd/syncclusterconfig/sync.go
  operator/internal/controller/redpanda/redpanda_controller.go
  operator/internal/controller/redpanda/redpanda_controller_test.go
Labels: backport, no-changelog

#578 acceptance-test: Add test that show case migration from helm to operator
  acceptance/features/migration.feature
  acceptance/go.mod
  acceptance/steps/cluster.go
  acceptance/steps/helm.go
  acceptance/steps/k8s.go
  acceptance/steps/register.go
  harpoon/internal/testing/panic.go
Labels: no-changelog

#754 [release/v2.4.x] Make ARN also optional in the operator
  operator/cmd/configurator/configurator.go
Labels: backport

#752 [main] operator: add annotation feature flag for restart cluster on config change (#748)
  operator/cmd/syncclusterconfig/sync.go
  operator/internal/controller/redpanda/redpanda_controller.go
  operator/internal/controller/redpanda/redpanda_controller_test.go
Labels: backport, no-changelog

#755 [K8S-495] operator: load RBAC rules from kube-builder artifacts
  .changes/unreleased/operator-Changed-20250423-123459.yaml
  go.work.sum
  operator/CHANGELOG.md
  operator/chart/README.md
  operator/chart/chart.go
  operator/chart/chart_test.go
  operator/chart/files/rbac/decommission.ClusterRole.yaml
  operator/chart/files/rbac/decommission.Role.yaml
  operator/chart/files/rbac/leader-election.ClusterRole.yaml
  operator/chart/files/rbac/leader-election.Role.yaml
  operator/chart/files/rbac/managed-decommission.ClusterRole.yaml
  operator/chart/files/rbac/managed-decommission.Role.yaml
  operator/chart/files/rbac/node-watcher.ClusterRole.yaml
  operator/chart/files/rbac/node-watcher.Role.yaml
  operator/chart/files/rbac/old-decommission.ClusterRole.yaml
  operator/chart/files/rbac/old-decommission.Role.yaml
  operator/chart/files/rbac/pvcunbinder.ClusterRole.yaml
  operator/chart/files/rbac/pvcunbinder.Role.yaml
  operator/chart/files/rbac/rack-awareness.ClusterRole.yaml
  operator/chart/files/rbac/rpk-debug-bundle.Role.yaml
  operator/chart/files/rbac/sidecar.Role.yaml
  operator/chart/files/rbac/v1-manager.ClusterRole.yaml
  operator/chart/files/rbac/v2-manager.ClusterRole.yaml
  operator/chart/files/rbac/v2-manager.Role.yaml
  operator/chart/rbac.go
  operator/chart/templates/_rbac.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
  operator/chart/values.yaml
  taskfiles/k8s.yml
Labels: v2.4.x, v2.3.x

#758 [release/v2.4.x] [K8S-495] operator: load RBAC rules from kube-builder artifacts
  .changes/unreleased/operator-Changed-20250423-123459.yaml
  operator/CHANGELOG.md
  operator/chart/README.md
  operator/chart/chart.go
  operator/chart/chart_test.go
  operator/chart/files/rbac/decommission.ClusterRole.yaml
  operator/chart/files/rbac/decommission.Role.yaml
  operator/chart/files/rbac/leader-election.ClusterRole.yaml
  operator/chart/files/rbac/leader-election.Role.yaml
  operator/chart/files/rbac/managed-decommission.ClusterRole.yaml
  operator/chart/files/rbac/managed-decommission.Role.yaml
  operator/chart/files/rbac/node-watcher.ClusterRole.yaml
  operator/chart/files/rbac/node-watcher.Role.yaml
  operator/chart/files/rbac/old-decommission.ClusterRole.yaml
  operator/chart/files/rbac/old-decommission.Role.yaml
  operator/chart/files/rbac/pvcunbinder.ClusterRole.yaml
  operator/chart/files/rbac/pvcunbinder.Role.yaml
  operator/chart/files/rbac/rack-awareness.ClusterRole.yaml
  operator/chart/files/rbac/rpk-debug-bundle.Role.yaml
  operator/chart/files/rbac/sidecar.Role.yaml
  operator/chart/files/rbac/v1-manager.ClusterRole.yaml
  operator/chart/files/rbac/v2-manager.ClusterRole.yaml
  operator/chart/files/rbac/v2-manager.Role.yaml
  operator/chart/rbac.go
  operator/chart/templates/_rbac.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
  operator/chart/values.yaml
  taskfiles/k8s.yml
Labels: backport

#759 [release/v2.3.x] [K8S-495] operator: load RBAC rules from kube-builder artifacts
  .changes/unreleased/operator-Changed-20250423-123459.yaml
  operator/CHANGELOG.md
  operator/chart/README.md
  operator/chart/chart.go
  operator/chart/chart_test.go
  operator/chart/files/rbac/decommission.ClusterRole.yaml
  operator/chart/files/rbac/decommission.Role.yaml
  operator/chart/files/rbac/leader-election.ClusterRole.yaml
  operator/chart/files/rbac/leader-election.Role.yaml
  operator/chart/files/rbac/managed-decommission.ClusterRole.yaml
  operator/chart/files/rbac/managed-decommission.Role.yaml
  operator/chart/files/rbac/node-watcher.ClusterRole.yaml
  operator/chart/files/rbac/node-watcher.Role.yaml
  operator/chart/files/rbac/old-decommission.ClusterRole.yaml
  operator/chart/files/rbac/old-decommission.Role.yaml
  operator/chart/files/rbac/pvcunbinder.ClusterRole.yaml
  operator/chart/files/rbac/pvcunbinder.Role.yaml
  operator/chart/files/rbac/rack-awareness.ClusterRole.yaml
  operator/chart/files/rbac/rpk-debug-bundle.Role.yaml
  operator/chart/files/rbac/sidecar.Role.yaml
  operator/chart/files/rbac/v1-manager.ClusterRole.yaml
  operator/chart/files/rbac/v2-manager.ClusterRole.yaml
  operator/chart/files/rbac/v2-manager.Role.yaml
  operator/chart/rbac.go
  operator/chart/templates/_rbac.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
  operator/chart/values.yaml
  taskfiles/k8s.yml
Labels: backport

#756 CEL patching: Add warnings to Template.Fixup
  .changes/unreleased/operator-Added-20250424-112217.yaml
  .changes/unreleased/operator-Deprecated-20250424-112329.yaml
  operator/CHANGELOG.md
  operator/api/vectorized/v1alpha1/cluster_types.go
  operator/api/vectorized/v1alpha1/zz_generated.deepcopy.go
  operator/cmd/configurator/fixup.go
  operator/config/crd/bases/redpanda.vectorized.io_clusters.yaml
  operator/pkg/clusterconfiguration/cel_macros.go
  operator/pkg/clusterconfiguration/cel_patcher.go
  operator/pkg/clusterconfiguration/cel_patcher_test.go
  operator/pkg/clusterconfiguration/configuration_cluster.go
  operator/pkg/clusterconfiguration/expander.go
Labels: run-kuttl-v1

#757 update CONTRIBUTING.md with links to Jira Releases
  CONTRIBUTING.md
Labels: no-changelog

#769 [main] operator: correct incorrect type marshalling in `GetValues`
  operator/api/redpanda/v1alpha2/redpanda_types.go
  operator/api/redpanda/v1alpha2/redpanda_types_test.go
Labels: backport, no-changelog

#768 [release/v2.4.x] operator: correct incorrect type marshalling in `GetValues`
  operator/api/redpanda/v1alpha2/redpanda_types.go
  operator/api/redpanda/v1alpha2/redpanda_types_test.go
Labels: backport

#765 [release/v2.4.x] operator: Fix inconsistency with superusers configuration ordering
  operator/internal/controller/redpanda/redpanda_controller_test.go
Labels: backport

#766 [release/v2.3.x] operator: Fix inconsistency with superusers configuration ordering
  operator/internal/controller/redpanda/redpanda_controller_test.go
Labels: backport

#772 acceptance-tests: Rewrite feature scenario to match expected english vocabulary
  acceptance/features/migration.feature
  acceptance/steps/helm.go
  acceptance/steps/register.go
Labels: no-changelog

#760 operator: cut release v25.1.1-beta2
  .changes/operator/v25.1.1-beta2.md
  .changes/unreleased/charts-operator-Changed-20250321-123010.yaml
  .changes/unreleased/operator-Changed-20250127-135909.yaml
  .changes/unreleased/operator-Changed-20250207-155651.yaml
  .changes/unreleased/operator-Changed-20250321-123010.yaml
  .changes/unreleased/operator-Fixed-20250129-173110.yaml
  .changes/unreleased/operator-Fixed-20250207-160109.yaml
  .changes/unreleased/operator-Removed-20250226-182037.yaml
  .changes/unreleased/operator-Removed-20250327-130201.yaml
  .changie.yaml
  charts/redpanda/README.md
  charts/redpanda/values.yaml
  operator/CHANGELOG.md
  operator/chart/Chart.yaml
  operator/chart/README.md
  operator/chart/templates/tests/create-topic-with-client-auth.yaml
  operator/chart/testdata/template-cases.golden.txtar
  operator/internal/lifecycle/testdata/cases.pools.golden.txtar
  operator/internal/lifecycle/testdata/cases.resources.golden.txtar
Labels: no-changelog

#785 [release/v2.4.x] operator: Remove obsolete managed decommission controller
  operator/api/redpanda/v1alpha2/redpanda_types.go
  operator/api/redpanda/v1alpha2/testdata/crd-docs.adoc
  operator/api/redpanda/v1alpha2/zz_generated.deepcopy.go
  operator/chart/chart_test.go
  operator/chart/files/rbac/managed-decommission.ClusterRole.yaml
  operator/chart/files/rbac/managed-decommission.Role.yaml
  operator/chart/rbac.go
  operator/chart/templates/_rbac.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
  operator/cmd/run/run.go
  operator/config/crd/bases/cluster.redpanda.com_redpandas.yaml
  operator/config/rbac/bases/operator/role.yaml
  operator/config/rbac/itemized/managed-decommission.yaml
  operator/internal/controller/manageddecommission/managed_decommission_controller.go
  operator/internal/controller/redpanda/redpanda_controller.go
  operator/internal/controller/redpanda/redpanda_controller_test.go
  operator/internal/controller/redpanda/testdata/role.yaml
  operator/internal/controller/vectorized/test/suite_test.go
  operator/pkg/resources/statefulset.go
  operator/pkg/resources/statefulset_test.go
  operator/pkg/resources/statefulset_update.go
  operator/tests/e2e/managed-decommission/00-assert.yaml
  operator/tests/e2e/managed-decommission/00-redpanda-cluster.yaml
  operator/tests/e2e/managed-decommission/01-assert.yaml
  operator/tests/e2e/managed-decommission/01-schedule-decommission.yaml
  operator/tests/e2e/managed-decommission/02-assert.yaml
  operator/tests/e2e/managed-decommission/02-probe.yaml
  operator/tests/e2e/managed-decommission/03-clean.yaml
  operator/tests/e2e/managed-decommission/README.txt
  taskfiles/k8s.yml
Labels: backport

#786 [release/v2.3.x] operator: Remove obsolete managed decommission controller
  operator/api/redpanda/v1alpha2/redpanda_types.go
  operator/api/redpanda/v1alpha2/testdata/crd-docs.adoc
  operator/api/redpanda/v1alpha2/zz_generated.deepcopy.go
  operator/chart/chart_test.go
  operator/chart/files/rbac/managed-decommission.ClusterRole.yaml
  operator/chart/files/rbac/managed-decommission.Role.yaml
  operator/chart/rbac.go
  operator/chart/templates/_rbac.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
  operator/cmd/run/run.go
  operator/config/crd/bases/cluster.redpanda.com_redpandas.yaml
  operator/config/rbac/bases/operator/role.yaml
  operator/config/rbac/itemized/managed-decommission.yaml
  operator/internal/controller/manageddecommission/managed_decommission_controller.go
  operator/internal/controller/redpanda/redpanda_controller.go
  operator/internal/controller/redpanda/redpanda_controller_test.go
  operator/internal/controller/redpanda/testdata/role.yaml
  operator/internal/controller/vectorized/test/suite_test.go
  operator/pkg/resources/statefulset.go
  operator/pkg/resources/statefulset_test.go
  operator/pkg/resources/statefulset_update.go
  operator/tests/e2e/managed-decommission/00-assert.yaml
  operator/tests/e2e/managed-decommission/00-redpanda-cluster.yaml
  operator/tests/e2e/managed-decommission/01-assert.yaml
  operator/tests/e2e/managed-decommission/01-schedule-decommission.yaml
  operator/tests/e2e/managed-decommission/02-assert.yaml
  operator/tests/e2e/managed-decommission/02-probe.yaml
  operator/tests/e2e/managed-decommission/03-clean.yaml
  operator/tests/e2e/managed-decommission/README.txt
  taskfiles/k8s.yml
Labels: backport

#790 operator: bump `go-git` from v5.11.0 to v5.13.0
  gen/go.mod
  gen/go.sum
  licenses/third_party.md
  operator/go.mod
  operator/go.sum
Labels: v2.3.x

#787 [v2.4.x] operator: over scope RBAC by default for backwards compat
  .changes/unreleased/operator-Added-20250430-130846.yaml
  operator/CHANGELOG.md
  operator/chart/README.md
  operator/chart/chart_test.go
  operator/chart/files/rbac/legacypermissions.ClusterRole.yaml
  operator/chart/files/rbac/legacypermissions.Role.yaml
  operator/chart/files/rbac/v2-manager.Role.yaml
  operator/chart/rbac.go
  operator/chart/templates/_rbac.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
  operator/chart/values.go
  operator/chart/values.schema.json
  operator/chart/values.yaml
  operator/chart/values_partial.gen.go
  operator/config/rbac/bases/operator/role.yaml
  operator/config/rbac/itemized/legacypermissions.yaml
  operator/config/rbac/itemized/v2-manager.yaml
  operator/internal/controller/legacypermissions/doc.go
  operator/internal/controller/legacypermissions/legacypermissions_test.go
  operator/internal/controller/redpanda/redpanda_controller.go
  operator/internal/controller/redpanda/redpanda_controller_test.go
  operator/internal/controller/redpanda/testdata/role.yaml
  taskfiles/k8s.yml
Labels: v2.3.x
