Repository redpanda-data/redpanda-operator, pull requests merged in 2025-09, with the labels that each got.

#1067 operator: Removed duplicated flag
  operator/chart/deployment.go
  operator/chart/templates/_deployment.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
Labels: no-changelog

#1066 Make name of Certificate custom resource configurable
  operator/chart/certificates.go
  operator/chart/service.go
  operator/chart/templates/_certificates.go.tpl
  operator/chart/templates/_service.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
Labels: no-changelog

#1069 Fix up the way image overrides work with nodepools and add a compat test
  operator/api/redpanda/v1alpha2/conversion/to_render.go
  operator/internal/lifecycle/testdata/cases.pools.golden.txtar
  operator/internal/lifecycle/testdata/cases.resources.golden.txtar
  operator/internal/lifecycle/testdata/cases.txtar
  operator/internal/lifecycle/testdata/cases.values.golden.txtar
  operator/internal/lifecycle/v2_test.go
Labels: no-changelog

#1070 charts/redpanda: allow overriding volumes
  .changes/unreleased/charts-redpanda-Fixed-20250908-172418.yaml
  charts/redpanda/chart/templates/_helpers.go.tpl
  charts/redpanda/helpers.go
  charts/redpanda/helpers_test.go
  charts/redpanda/testdata/template-cases.txtar
Labels: v2.4.x, v25.1.x

#1086 *: prevent circular imports
  charts/console/go.mod
  charts/console/go.sum
  charts/redpanda/configmap.tpl.go
  charts/redpanda/go.mod
  charts/redpanda/go.sum
  charts/redpanda/values.go
  charts/redpanda/values_test.go
  gen/go.mod
  gen/go.sum
  go.work.sum
  harpoon/go.sum
  operator/api/vectorized/v1alpha1/cluster_types.go
  operator/cmd/bootstrap/bootstrap.go
  operator/cmd/configurator/bootstrap.go
  operator/cmd/configurator/configurator.go
  operator/cmd/configurator/fixup.go
  operator/cmd/run/run.go
  operator/go.mod
  operator/internal/controller/redpanda/redpanda_controller.go
  operator/internal/controller/vectorized/cluster_controller.go
  operator/internal/controller/vectorized/cluster_controller_attached_resources.go
  operator/internal/controller/vectorized/cluster_controller_configuration.go
  operator/internal/controller/vectorized/cluster_controller_test.go
  operator/internal/controller/vectorized/test/cluster_controller_configuration_test.go
  operator/pkg/resources/configmap.go
  operator/pkg/resources/configmap_test.go
  operator/pkg/resources/configuration.go
  operator/pkg/resources/resource_integration_test.go
  operator/pkg/resources/statefulset.go
  pkg/clusterconfiguration/cel_macros.go
  pkg/clusterconfiguration/cel_patcher.go
  pkg/clusterconfiguration/cel_patcher_test.go
  pkg/clusterconfiguration/configuration_cluster.go
  pkg/clusterconfiguration/configuration_combined.go
  pkg/clusterconfiguration/configuration_node.go
  pkg/clusterconfiguration/configuration_rpk.go
  pkg/clusterconfiguration/configuration_test.go
  pkg/clusterconfiguration/expander.go
  pkg/clusterconfiguration/serialization_test.go
  pkg/clusterconfiguration/types.go
  pkg/go.mod
  pkg/go.sum
  pkg/lint/lint_test.go
  pkg/secrets/secrets.go
  pkg/secrets/secrets_test.go
Labels: no-changelog

#1090 *: stop leaking (most) etcd procs
  operator/internal/testutils/setup_envtest.go
  pkg/kube/envexpander_test.go
Labels: no-changelog, v2.4.x, v25.1.x

#1097 Make ordering of statefulset processing consistent in rendering
  charts/redpanda/chart/templates/_configmap.go.tpl
  charts/redpanda/configmap.tpl.go
  operator/api/redpanda/v1alpha2/conversion/to_render.go
  operator/internal/lifecycle/testdata/cases.pools.golden.txtar
  operator/internal/lifecycle/testdata/cases.resources.golden.txtar
  operator/internal/lifecycle/testdata/cases.txtar
  operator/internal/lifecycle/testdata/cases.values.golden.txtar
Labels: no-changelog

#1102 *: upgrade testcontainers to latest
  acceptance/go.mod
  acceptance/go.sum
  charts/connectors/go.mod
  charts/connectors/go.sum
  charts/console/go.mod
  charts/console/go.sum
  charts/redpanda/go.mod
  charts/redpanda/go.sum
  gen/go.mod
  gen/go.sum
  go.work.sum
  gotohelm/go.mod
  gotohelm/go.sum
  gotohelm/testdata/src/example/go.mod
  gotohelm/testdata/src/example/go.sum
  harpoon/go.mod
  harpoon/go.sum
  licenses/third_party.md
  licenseupdater/go.mod
  licenseupdater/go.sum
  operator/go.mod
  operator/go.sum
  pkg/go.mod
  pkg/go.sum
Labels: no-changelog, v25.1.x
