Repository redpanda-data/redpanda-operator, pull requests merged in 2025-03, with the labels that each got.

#497 [release/v2.3.x] Add backport CLI (#490)
  .backportrc.json
  CONTRIBUTING.md
  ci/backport.nix
  ci/files/backport-package-lock.json
  ci/overlay.nix
  flake.nix
Labels: backport

#501 [release/v2.3.x] charts/redpadna: Align go module path to include v5 version of the helm chart
  charts/redpanda/chart_template_test.go
  charts/redpanda/chart_test.go
  charts/redpanda/client/client.go
  charts/redpanda/client/client_test.go
  charts/redpanda/client_test.go
  charts/redpanda/go.mod
  charts/redpanda/helpers_test.go
  charts/redpanda/values_partial_test.go
Labels: backport

#495 Add backport action
  .backportrc.json
  .github/labels.yml
  .github/workflows/auto-approve-backport.yml
  .github/workflows/backport.yml
  .github/workflows/changelog.yml
  .github/workflows/labels.yml
Labels: v2.3.9, no-changelog

#504 [release/v2.3.x] Add backport action (#495)
  .backportrc.json
  .github/labels.yml
  .github/workflows/auto-approve-backport.yml
  .github/workflows/backport.yml
  .github/workflows/changelog.yml
  .github/workflows/labels.yml
Labels: backport

#506 Add licenseupdater organization for re-use in OSS licenses
  licenseupdater/config.go
  licenseupdater/main.go
  licenseupdater/main_test.go
  licenseupdater/templates/MIT.header.tmpl
  licenseupdater/templates/MIT.md.tmpl
  licenseupdater/templates/MIT.short
Labels: no-changelog

#511 [release/v2.3.x] pkg/kube: support nested dialers
  pkg/kube/dialer.go
  pkg/kube/dialer_test.go
Labels: backport

#514 gotohelm: support struct embedding in `helmette.Unwrap`
  pkg/go.mod
  pkg/go.sum
  pkg/gotohelm/helmette/shims.go
  pkg/gotohelm/testdata/src/example/go.mod
  pkg/gotohelm/testdata/src/example/go.sum
  pkg/gotohelm/testdata/src/example/typing/embedding.go
  pkg/gotohelm/testdata/src/example/typing/embedding.rewritten.go
  pkg/gotohelm/testdata/src/example/typing/embedding.yaml
  pkg/gotohelm/testdata/src/example/typing/typing.go
  pkg/gotohelm/testdata/src/example/typing/typing.rewritten.go
  pkg/gotohelm/testdata/src/example/typing/typing.yaml
  pkg/gotohelm/transpiler_test.go
Labels: no-changelog

#513 gen: fix partial generation of embedded structs
  gen/partial/partial.go
  gen/partial/partial_test.go
  gen/partial/testdata/partial.go
Labels: no-changelog

#517 [release/v2.3.x] workflows: improve changelog GHA error message
  .github/workflows/changelog.yml
  CONTRIBUTING.md
Labels: backport

#522 [release/v2.3.x] gotohelm: support struct embedding in `helmette.Unwrap`
  pkg/go.mod
  pkg/go.sum
  pkg/gotohelm/helmette/shims.go
  pkg/gotohelm/testdata/src/example/go.mod
  pkg/gotohelm/testdata/src/example/go.sum
  pkg/gotohelm/testdata/src/example/typing/embedding.go
  pkg/gotohelm/testdata/src/example/typing/embedding.rewritten.go
  pkg/gotohelm/testdata/src/example/typing/embedding.yaml
  pkg/gotohelm/testdata/src/example/typing/typing.go
  pkg/gotohelm/testdata/src/example/typing/typing.rewritten.go
  pkg/gotohelm/testdata/src/example/typing/typing.yaml
  pkg/gotohelm/transpiler_test.go
Labels: backport

#523 [release/v2.3.x] gen: fix partial generation of embedded structs
  gen/partial/partial.go
  gen/partial/partial_test.go
  gen/partial/testdata/partial.go
Labels: backport

#535 *: require usage of `github.com/cockroachdb/errors`
  .golangci.yml
  charts/redpanda/chart_test.go
  charts/redpanda/client/client.go
  charts/redpanda/go.mod
  harpoon/go.mod
  harpoon/tablegenerator/generator.go
  licenseupdater/check.go
  licenseupdater/config.go
  licenseupdater/go.mod
  licenseupdater/go.sum
  operator/api/redpanda/v1alpha2/common.go
  operator/api/redpanda/v1alpha2/user_types.go
  operator/cmd/configurator/configurator.go
  operator/cmd/ready/ready.go
  operator/cmd/run/run.go
  operator/cmd/sidecar/sidecar.go
  operator/cmd/syncclusterconfig/sync.go
  operator/internal/controller/redpanda/redpanda_decommission_controller.go
  operator/internal/controller/redpanda/redpanda_node_pvc_controller.go
  operator/internal/controller/redpanda/resource_controller.go
  operator/internal/controller/redpanda/resource_controller_test.go
  operator/internal/controller/redpanda/topic_controller.go
  operator/internal/controller/vectorized/cluster_controller.go
  operator/internal/controller/vectorized/cluster_controller_attached_resources.go
  operator/internal/controller/vectorized/cluster_controller_configuration.go
  operator/internal/controller/vectorized/console_controller.go
  operator/internal/decommissioning/chained_fetcher.go
  operator/internal/decommissioning/delayed_cache_test.go
  operator/internal/decommissioning/helm_fetcher.go
  operator/internal/decommissioning/statefulset_decomissioner.go
  operator/internal/probes/broker_test.go
  operator/internal/probes/server.go
  operator/internal/testutils/setup_envtest.go
  operator/pkg/client/errors.go
  operator/pkg/client/factory.go
  operator/pkg/client/schemas/syncer.go
  operator/pkg/console/configmap.go
  operator/pkg/k3d/k3d_test.go
  operator/pkg/resources/certmanager/ca_certificate_bundle_test.go
  operator/pkg/resources/certmanager/pki.go
  operator/pkg/resources/certmanager/type_helpers.go
  operator/pkg/resources/configmap.go
  operator/pkg/resources/statefulset.go
  operator/pkg/resources/statefulset_scale.go
  operator/pkg/resources/statefulset_test.go
  operator/pkg/resources/statefulset_update.go
  operator/webhooks/redpanda/console_webhook.go
  pkg/kube/dialer.go
  pkg/kube/dialer_test.go
Labels: no-changelog

#547 [release/v2.3.x] Remove availableReplicas check (#545)
  operator/internal/controller/redpanda/redpanda_decommission_controller.go
Labels: backport

#505 Add actions for notifying of pending prs, closing stale prs and switch user for auto-backports
  .github/branches.yml
  .github/labels.yml
  .github/workflows/backport.yml
  .github/workflows/pending-prs.yml
  .github/workflows/scripts/pending-prs
  .github/workflows/stale-prs.yml
  Taskfile.yml
  flake.nix
Labels: v2.3.9, no-changelog

#551 [release/v2.3.x] *: require usage of `github.com/cockroachdb/errors`
  .golangci.yml
  charts/redpanda/chart_test.go
  charts/redpanda/client/client.go
  charts/redpanda/go.mod
  harpoon/go.mod
  harpoon/tablegenerator/generator.go
  licenseupdater/check.go
  licenseupdater/config.go
  licenseupdater/go.mod
  licenseupdater/go.sum
  operator/api/redpanda/v1alpha2/common.go
  operator/api/redpanda/v1alpha2/user_types.go
  operator/cmd/configurator/configurator.go
  operator/cmd/ready/ready.go
  operator/cmd/run/run.go
  operator/cmd/sidecar/sidecar.go
  operator/internal/controller/redpanda/redpanda_decommission_controller.go
  operator/internal/controller/redpanda/redpanda_node_pvc_controller.go
  operator/internal/controller/redpanda/resource_controller.go
  operator/internal/controller/redpanda/resource_controller_test.go
  operator/internal/controller/redpanda/topic_controller.go
  operator/internal/controller/vectorized/cluster_controller.go
  operator/internal/controller/vectorized/cluster_controller_attached_resources.go
  operator/internal/controller/vectorized/cluster_controller_configuration.go
  operator/internal/controller/vectorized/console_controller.go
  operator/internal/decommissioning/chained_fetcher.go
  operator/internal/decommissioning/delayed_cache_test.go
  operator/internal/decommissioning/helm_fetcher.go
  operator/internal/decommissioning/statefulset_decomissioner.go
  operator/internal/probes/broker_test.go
  operator/internal/probes/server.go
  operator/internal/testutils/setup_envtest.go
  operator/pkg/client/errors.go
  operator/pkg/client/factory.go
  operator/pkg/client/schemas/syncer.go
  operator/pkg/console/configmap.go
  operator/pkg/k3d/k3d_test.go
  operator/pkg/resources/certmanager/ca_certificate_bundle_test.go
  operator/pkg/resources/certmanager/pki.go
  operator/pkg/resources/certmanager/type_helpers.go
  operator/pkg/resources/configmap.go
  operator/pkg/resources/statefulset.go
  operator/pkg/resources/statefulset_scale.go
  operator/pkg/resources/statefulset_test.go
  operator/pkg/resources/statefulset_update.go
  operator/webhooks/redpanda/console_webhook.go
  pkg/kube/dialer.go
  pkg/kube/dialer_test.go
Labels: backport, no-changelog

#557 [release/v2.3.x] add `actionlint` to CI
  .github/workflows/changelog.yml
  .github/workflows/comment_added.yml
  .github/workflows/jira_issue_manage.yml
  Taskfile.yml
  flake.nix
Labels: backport

#556 Fix actionlint complaints of `pending-prs.yml`
  .github/workflows/pending-prs.yml
Labels: no-changelog

#560 fix build caching of go binaries
  taskfiles/build.yml
Labels: no-changelog

#561 Testing: one MockAdminAPI per cluster
  operator/internal/controller/vectorized/test/cluster_controller_configuration_test.go
  operator/internal/controller/vectorized/test/cluster_controller_scale_test.go
  operator/internal/controller/vectorized/test/cluster_controller_test.go
  operator/internal/controller/vectorized/test/console_controller_test.go
  operator/internal/controller/vectorized/test/suite_test.go
Labels: no-changelog

#570 pkg: Remove files that are present in gotohelm package
  pkg/gotohelm/testdata/src/example/typing/embedding.rewritten.go
  pkg/gotohelm/testdata/src/example/typing/embedding.yaml
Labels: no-changelog

#548 Trigger CRD docs automation on new releases rather than pushes to main
  .github/workflows/dispatch-crd-docs.yml
Labels: stale

#573 operator: Return errors with stacktrace
  operator/internal/controller/redpanda/redpanda_controller.go
Labels: no-changelog

#575 gotohelm: add support for subchart aliases
  gotohelm/gochart.go
  gotohelm/gochart_test.go
  gotohelm/testdata/subchart/dependency-excluded-by-default/templates/config-map.tpl
  gotohelm/testdata/subchart/dependency-included-by-default/Chart.lock
  gotohelm/testdata/subchart/dependency-included-by-default/Chart.yaml
  gotohelm/testdata/subchart/dependency-included-by-default/templates/config-map.tpl
  gotohelm/testdata/subchart/dependency-included-by-default/values.yaml
  gotohelm/testdata/subchart/dependency/templates/config-map.tpl
  gotohelm/testdata/subchart/root/templates/config-map.tpl
  gotohelm/testdata/subchart/values-overwrite/templates/config-map.tpl
Labels: no-changelog

#576 Add release/v25.1.x and release/v2.4.x to active branches
  .backportrc.json
  .github/branches.yml
  README.md
  pkg/lint/lint_test.go
Labels: no-changelog, v25.1.x

#583 [release/v2.4.x] operator: Return errors with stacktrace
  operator/internal/controller/redpanda/redpanda_controller.go
Labels: backport

#584 [release/v2.3.x] operator: Return errors with stacktrace
  operator/internal/controller/redpanda/redpanda_controller.go
Labels: backport

#563 ci: change BK pool used and add push nightlies to new ECR registry
  .buildkite/pipeline.yml
  .buildkite/testsuite.yml
  gen/pipeline/pipeline.go
  taskfiles/ci.yml
Labels: no-changelog

#592 Start certificate watchers
  .changes/unreleased/operator-Fixed-20250328-112231.yaml
  operator/CHANGELOG.md
  operator/cmd/run/run.go
Labels: no-changelog

#552 Switch integration, acceptance, and kuttl-v1 CI tests to required
  .buildkite/testsuite.yml
  gen/pipeline/pipeline.go
Labels: backport, no-changelog, v25.1.x, v2.4.x, v2.3.x

#596 [release/v25.1.x] Start certificate watchers (#592)
  .changes/unreleased/operator-Fixed-20250328-112231.yaml
  operator/CHANGELOG.md
  operator/cmd/run/run.go
Labels: backport

#591 [release/v2.3.x] ci: change BK pool used and add push nightlies to new ECR registry (#563)
  .buildkite/pipeline.yml
  .buildkite/testsuite.yml
  gen/pipeline/pipeline.go
  taskfiles/ci.yml
Labels: backport

#590 [release/v2.4.x] ci: change BK pool used and add push nightlies to new ECR registry (#563)
  .buildkite/pipeline.yml
  .buildkite/testsuite.yml
  gen/pipeline/pipeline.go
  taskfiles/ci.yml
Labels: backport

#589 [release/v25.1.x] ci: change BK pool used and add push nightlies to new ECR registry (#563)
  .buildkite/pipeline.yml
  .buildkite/testsuite.yml
  gen/pipeline/pipeline.go
  taskfiles/ci.yml
Labels: backport

#569 Expand cloud secrets
  licenses/third_party.md
  operator/cmd/configurator/bootstrap.go
  operator/cmd/configurator/configurator.go
  operator/cmd/run/run.go
  operator/go.mod
  operator/go.sum
  operator/internal/controller/vectorized/cluster_controller.go
  operator/internal/controller/vectorized/cluster_controller_configuration.go
  operator/pkg/clusterconfiguration/expander.go
  operator/pkg/resources/configuration/configuration.go
  operator/pkg/resources/configuration/configuration_test.go
Labels: no-changelog

#597 [release/v2.4.x] Start certificate watchers (#592)
  .changes/unreleased/operator-Fixed-20250328-112231.yaml
  operator/CHANGELOG.md
  operator/cmd/run/run.go
Labels: backport

#588 operator: default `useFlux` to `false`
  .changes/unreleased/operator-Changed-20250327-160013.yaml
  .changes/unreleased/operator-Changed-20250327-160111.yaml
  .changes/unreleased/operator-Changed-20250327-160328.yaml
  operator/CHANGELOG.md
  operator/api/redpanda/v1alpha2/redpanda_types.go
  operator/api/redpanda/v1alpha2/redpanda_types_test.go
  operator/api/redpanda/v1alpha2/testdata/crd-docs.adoc
  operator/cmd/run/run.go
  operator/config/crd/bases/cluster.redpanda.com_redpandas.yaml
  operator/internal/controller/redpanda/redpanda_controller_test.go
  operator/internal/controller/vectorized/test/redpanda_controller_test.go
Labels: v2.4.x

#598 [release/v2.3.x] Start certificate watchers (#592)
  .changes/unreleased/operator-Fixed-20250328-112231.yaml
  operator/CHANGELOG.md
  operator/cmd/run/run.go
Labels: backport

#543 V1 drop drift controller
  operator/cmd/run/run.go
  operator/internal/controller/vectorized/cluster_controller.go
  operator/internal/controller/vectorized/cluster_controller_configuration.go
  operator/internal/controller/vectorized/cluster_controller_configuration_drift.go
  operator/internal/controller/vectorized/cluster_controller_configuration_drift_test.go
  operator/internal/controller/vectorized/test/cluster_controller_configuration_test.go
  operator/internal/controller/vectorized/test/suite_test.go
  operator/pkg/resources/configmap.go
  operator/pkg/resources/configuration/patch.go
  operator/pkg/resources/configuration/patch_test.go
  operator/pkg/resources/resource.go
  operator/pkg/resources/secret.go
  operator/pkg/resources/statefulset.go
Labels: no-changelog
