Repository redpanda-data/redpanda-operator, pull requests merged in 2025-07, with the labels that each got.

#954 Backport/opv2 bootstrap command
  operator/cmd/bootstrap/bootstrap.go
  operator/cmd/configurator/bootstrap.go
  operator/cmd/configurator/configurator.go
  operator/cmd/main.go
  operator/pkg/clusterconfiguration/cel_patcher.go
  operator/pkg/clusterconfiguration/configuration_cluster.go
  operator/pkg/clusterconfiguration/configuration_combined.go
  operator/pkg/clusterconfiguration/configuration_node.go
Labels: run-kuttl-v1

#956 [release/v25.1.x] operator: Add option to opt-out from User password generation
  .changes/unreleased/operator-Added-20250630-182854.yaml
  operator/api/applyconfiguration/redpanda/v1alpha2/password.go
  operator/api/redpanda/v1alpha2/testdata/crd-docs.adoc
  operator/api/redpanda/v1alpha2/user_types.go
  operator/config/crd/bases/cluster.redpanda.com_users.yaml
  operator/pkg/client/users/client.go
  operator/pkg/client/users/client_test.go
Labels: backport

#970 [release/v2.4.x] release: fix tag pattern
  .github/workflows/release.yml
Labels: backport

#958 [release/v2.3.x] operator: Add option to opt-out from User password generation
  .changes/unreleased/operator-Added-20250630-182854.yaml
  flake.nix
  operator/api/applyconfiguration/redpanda/v1alpha2/password.go
  operator/api/redpanda/v1alpha2/testdata/crd-docs.adoc
  operator/api/redpanda/v1alpha2/user_types.go
  operator/config/crd/bases/cluster.redpanda.com_users.yaml
  operator/pkg/client/users/client.go
  operator/pkg/client/users/client_test.go
Labels: backport

#977 [release/v25.1.x] operator: use default AWS AZ ID topology label key
  operator/cmd/configurator/configurator.go
Labels: backport

#979 [release/v2.4.x] operator: Add option to disable cluster configuration in sidecar
  .changes/unreleased/operator-Fixed-20250625-101214.yaml
  operator/api/redpanda/v1alpha2/redpanda_clusterspec_types.go
  operator/api/redpanda/v1alpha2/testdata/crd-docs.adoc
  operator/api/redpanda/v1alpha2/zz_generated.deepcopy.go
  operator/cmd/sidecar/sidecar.go
  operator/cmd/syncclusterconfig/superusers.go
  operator/cmd/syncclusterconfig/sync.go
  operator/cmd/syncclusterconfig/sync_test.go
  operator/config/crd/bases/cluster.redpanda.com_redpandas.yaml
  operator/crd-docs-templates/gv_details.tpl
  operator/crd-docs-templates/gv_list.tpl
  operator/crd-docs-templates/type.tpl
  operator/crd-docs-templates/type_members.tpl
  operator/crd-ref-docs-config.yaml
  operator/internal/configwatcher/configwatcher.go
  operator/internal/controller/redpanda/redpanda_controller.go
  operator/internal/controller/redpanda/redpanda_controller_test.go
  taskfiles/k8s.yml
Labels: backport

#991 operator: Bump helm and rpk depedency to resolve snyk findinds
  acceptance/go.mod
  acceptance/go.sum
  acceptance/steps/cluster.go
  charts/connectors/go.mod
  charts/connectors/go.sum
  charts/console/go.mod
  charts/console/go.sum
  charts/redpanda/go.mod
  charts/redpanda/go.sum
  gen/go.mod
  gen/go.sum
  go.work.sum
  gotohelm/go.mod
  gotohelm/go.sum
  gotohelm/testdata/src/example/go.mod
  gotohelm/testdata/src/example/go.sum
  harpoon/go.mod
  harpoon/go.sum
  harpoon/internal/testing/strings.go
  licenses/third_party.md
  licenseupdater/go.mod
  licenseupdater/go.sum
  operator/cmd/syncclusterconfig/sync.go
  operator/go.mod
  operator/go.sum
  operator/internal/testenv/testenv.go
  pkg/go.mod
  pkg/go.sum
  pkg/lint/lint_test.go
Labels: no-changelog

#996 [release/v25.1.x] *: Bump github.com/go-viper/mapstructure/v2 to v2.3.0
  acceptance/go.mod
  acceptance/go.sum
  charts/connectors/go.mod
  charts/connectors/go.sum
  charts/console/go.mod
  charts/console/go.sum
  charts/redpanda/go.mod
  charts/redpanda/go.sum
  gen/go.mod
  gen/go.sum
  licenses/third_party.md
  operator/go.mod
  operator/go.sum
Labels: backport

#997 [release/v2.4.x] *: Bump github.com/go-viper/mapstructure/v2 to v2.3.0
  acceptance/go.mod
  acceptance/go.sum
  charts/connectors/go.mod
  charts/connectors/go.sum
  charts/console/go.mod
  charts/console/go.sum
  charts/redpanda/go.mod
  charts/redpanda/go.sum
  gen/go.mod
  gen/go.sum
  licenses/third_party.md
  operator/go.mod
  operator/go.sum
Labels: backport

#998 [release/v2.3.x] *: Bump github.com/go-viper/mapstructure/v2 to v2.3.0
  acceptance/go.mod
  acceptance/go.sum
  charts/connectors/go.mod
  charts/connectors/go.sum
  charts/console/go.mod
  charts/console/go.sum
  charts/redpanda/go.mod
  charts/redpanda/go.sum
  gen/go.mod
  gen/go.sum
  licenses/third_party.md
  operator/go.mod
  operator/go.sum
Labels: backport

#1010 Test fix: wrap initial version fetching in retry block
  operator/internal/controller/redpanda/redpanda_controller_test.go
Labels: no-changelog
