Repository redpanda-data/redpanda-operator, pull requests merged in 2025-08, with the labels that each got.

#1022 operator: fix helm install with crds.enabled and --wait
  .changes/unreleased/operator-Fixed-20250807-121401.yaml
  operator/chart/chart.go
  operator/chart/deployment.go
  operator/chart/pre_install_crd_job.go
  operator/chart/rbac.go
  operator/chart/serviceaccount.go
  operator/chart/templates/_chart.go.tpl
  operator/chart/templates/_deployment.go.tpl
  operator/chart/templates/_post-install-crd-job.go.tpl
  operator/chart/templates/_rbac.go.tpl
  operator/chart/templates/_serviceaccount.go.tpl
  operator/chart/testdata/template-cases.golden.txtar
Labels: v25.1.x

#1027 redpanda: use service discovery for client construction
  charts/redpanda/.helmignore
  charts/redpanda/chart_test.go
  charts/redpanda/client/client.go
  charts/redpanda/client/client_test.go
  charts/redpanda/client/outofclusterdns_integration.go
  charts/redpanda/client_test.go
  charts/redpanda/service_internal.go
  charts/redpanda/templates/_values.go.tpl
  charts/redpanda/values.go
  gen/go.sum
Labels: no-changelog, v2.4.x, v25.1.x

#1034 update RCL
  licenses/RCL.md
  licenseupdater/templates/RCL.md.tmpl
  licenseupdater/testdata/licenses/RCL.md.golden
Labels: no-changelog

#1032 Drop the critical configuration hash annotation
  .changes/unreleased/operator-Removed-20250813-154834.yaml
  operator/internal/controller/vectorized/cluster_controller.go
  operator/internal/controller/vectorized/cluster_controller_attached_resources.go
  operator/internal/controller/vectorized/cluster_controller_configuration.go
  operator/internal/controller/vectorized/test/cluster_controller_configuration_test.go
  operator/pkg/clusterconfiguration/configuration_cluster.go
  operator/pkg/clusterconfiguration/configuration_combined.go
  operator/pkg/resources/configmap.go
  operator/pkg/resources/resource.go
  operator/pkg/resources/statefulset.go
  operator/pkg/resources/statefulset_update.go
Labels: v25.1.x

#1045 pkg/kube: extract `Syncer` from lifecycle client
  Taskfile.yml
  harpoon/go.mod
  harpoon/go.sum
  operator/internal/controller/redpanda/resource_controller.go
  operator/internal/lifecycle/client.go
  operator/internal/lifecycle/client_test.go
  operator/internal/lifecycle/constants.go
  operator/internal/lifecycle/helpers.go
  operator/internal/lifecycle/interfaces_test.go
  operator/internal/lifecycle/v2_node_pools.go
  pkg/go.mod
  pkg/go.sum
  pkg/kube/ctl.go
  pkg/kube/ctl_test.go
  pkg/kube/syncer.go
  pkg/kube/syncer_test.go
  pkg/kube/util.go
Labels: no-changelog, v25.1.x

#1053 gen: respect `yaml` tags in paritialization
  gen/partial/partial.go
  gen/partial/partial_test.go
  gen/partial/testdata/partial.go
Labels: no-changelog, v25.1.x
